server:          true
auto:            true
server_port:     4000
analytics_token: 'UA-XXXXXXXX-X'

markdown: rdiscount
rdiscount:
  extensions: [smart, footnotes]

pygments:  false
permalink: /:categories/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
